[project]
name = "generator-api"
version = "0.1.0"
description = ""
authors = [{ name = "4l3j0Ok", email = "alejofsarmiento@gmail.com" }]
requires-python = ">=3.14"
dependencies = [
    "jinja2>=3.1.6,<4",
    "fastapi[standard]>=0.128.0,<1",
    "requests>=2.32.5,<3",
    "markdown>=3.7,<4",
]
